### ISSUE TITLE
[Enhancement]: New release requested

### ISSUE THREAD

**Issue by barryprice** [snapcrafters/irssi#12]
### What changes would you like?

We merged a workaround for building the 1.4.x series a while ago:

https://github.com/snapcrafters/irssi/pull/11

The latest/edge 1.4.2 is stable for me, and I've been using it for a few months now.

Can we consider promoting 1.4.2 to at least latest/beta (if not latest/stable), and running a fresh build to get 1.4.3, a bugfix release, into latest/edge?

https://github.com/irssi/irssi/releases/tag/1.4.3

### Any extra information?

Apologies if this isn't the right place to make this request, happy to move it elsewhere.

**Comment by popey** [comment]
Thanks @barryprice 
I have tested the latest build (1.4.5) and it should be released to stable/beta.
Releases 848 through 853

**Comment by barryprice** [comment]
Oh fantastic, thank you!

Is there anything I can usefully do to help get the 1.4.x releases promoted to latest/beta or even latest/stable?

The 1.2.3 release is almost two and a half years old at this point.

**Comment by popey** [comment]
1.4.5 is now in the stable channel
